apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
spec:
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: devops-map
