version: "3"

networks:
    laravel:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8088:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: devops
            MYSQL_USER: devops
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel
