version: "3"

networks:
    laravel:

services:
    nginx:
        build:
            context: .
            dockerfile: Web.Dockerfile
        image: nginx:stable-alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8088:80"
        depends_on:
            - app
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: devops
            MYSQL_USER: devops
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        tty: true
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "9010:9000"
        networks:
            - laravel

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus:/etc/prometheus
volumes:
    dbdata:
        driver: local
