apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - secretName: secret-tls
  rules:
    - host: devops.com
      http:
        paths:
          - backend:
              serviceName: devops-service
              servicePort: 80
