apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

resources:
  - nginx_configMap.yaml
  - nginx_deployment.yaml
  - nginx_service.yaml
  - deployment.yaml
  - service.yaml
  - configMap.yaml
