kind: Service
apiVersion: v1
metadata:
  name: devops
  labels:
    tier: backend
spec:
  selector:
    app: devops
    tier: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
